- name: "install haproxy"
  yum:
    name: haproxy
    state: present
- name: "copy haproxy.cfg"
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify:
    - restart haproxy
