    - name: "配置ceph软件源"
      yum_repository:
         file: ceph
         name: '{{ item.name }}'
         description: '{{ item.description}}'
         baseurl: '{{ item.baseurl }}'
         gpgkey: "https://mirrors.aliyun.com/ceph/keys/release.asc"
         gpgcheck: yes
         enabled: yes
      with_items:
         - { name: "Ceph",description: "Ceph packages for $basearch",baseurl: "https://mirrors.aliyun.com/ceph/rpm-nautilus/el7/$basearch" }
         - { name: "Ceph-noarch",description: "Ceph noarch packages",baseurl: "https://mirrors.aliyun.com/ceph/rpm-nautilus/el7/noarch" }
         - { name: "ceph-source",description: "Ceph source packages",baseurl: "https://mirrors.aliyun.com/ceph/rpm-nautilus/el7/SRPMS" }
      tags: ceph
    - name: "安装ceph客户端"
      yum:
         update_cache: yes
         name: "{{ item.line }}"
         state: latest
      with_items:
         - {line: 'leveldb'}
         - {line: 'libaio'}
         - {line: 'libbabeltrace'}
         - {line: 'libcephfs2'}
         - {line: 'librados2'}
         - {line: 'libradosstriper1'}
         - {line: 'librbd1'}
         - {line: 'librgw2'}
         - {line: 'lttng-ust'}
         - {line: 'python-cephfs'}
         - {line: 'python-chardet'}
         - {line: 'python-ipaddress'}
         - {line: 'python-prettytable'}
         - {line: 'python-rados'}
         - {line: 'python-rbd'}
         - {line: 'python-requests'}
         - {line: 'python-rgw'}
         - {line: 'python-six'}
         - {line: 'python-urllib3'}
         - {line: 'userspace-rcu'}
         - {line: 'ceph-fuse'}
         - {line: 'ceph-common'}
      tags: ceph