- name: "add Docker repo"
  yum_repository:
    file: docker-ce
    name: "docker-ce-stable"
    description: "Docker CE Stable - $basearch"
    baseurl: "https://mirrors.aliyun.com/docker-ce/linux/centos/7/$basearch/stable"
    gpgkey: "https://mirrors.aliyun.com/docker-ce/linux/centos/gpg"
    gpgcheck: yes
    enabled: yes
  tags: docker_repo
  when: yum_config_internet
- name: "install Docker-ce"
  yum:
    update_cache: yes
    name: 'docker-ce{% if docker_version is defined and docker_version != ""  %}-{{ docker_version }}{% endif %}'
    state: installed
- name: "start Docker service"
  systemd:
    name: docker
    state: started
- name: "touch daemon.json"
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker
- name: "restart Docker"
  systemd:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: restarted