- name: fail when hostname is not specified
  fail:
    msg: "hostname not specified"
  when:
    - hostname is not defined
- name: "修改主机名"
  hostname:
    name: "{{ hostname|quote }}"
  tags: hostname
- name: "设置主机名ip高亮显示"
  copy:
    src: "ipenv.sh"
    dest: "/etc/profile.d/"
  tags: os_env
- name: "设置时区"
  timezone:
    name: Asia/Shanghai
- name: "添加阿里云软件源"
  yum_repository:
    file: CentOS-Base
    name: '{{ item.name }}'
    description: '{{ item.description}}'
    baseurl: '{{ item.baseurl }}'
    gpgkey: "https://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7"
    failovermethod: priority
    gpgcheck: yes
    enabled: yes
  with_items:
    - { name: "base",description: "CentOS-$releasever",baseurl: "https://mirrors.aliyun.com/centos/$releasever/os/$basearch/" }
    - { name: "updates",description: "CentOS-$releasever",baseurl: "https://mirrors.aliyun.com/centos/$releasever/updates/$basearch/" }
    - { name: "extras",description: "CentOS-$releasever",baseurl: "https://mirrors.aliyun.com/centos/$releasever/extras/$basearch/" }
  tags: CentOS-Base
- name: "添加EPEL软件源"
  yum_repository:
    file: epel
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    baseurl: "https://mirrors.aliyun.com/epel/7/$basearch"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"
    failovermethod: priority
    gpgcheck: no
    enabled: yes
  tags: epel
- name: "安装chrony"
  yum:
    name: "chrony"
    state: installed
  tags: ntp
- name: "配置chrony服务"
  copy:
    src: "chrony.conf"
    dest: "/etc/chrony.conf"
  notify: 
    - restart chrony
  tags: ntp
- name: "关闭交换分区"
  shell: swapoff -a
- name: "关闭selinux"
  selinux:
    state: disabled
  tags: selinux
- name: "关闭防火墙"
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  tags: firewalld
- name: "修改ssh配置"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "UseDNS", line: "UseDNS no" }
    - { regexp: "AddressFamily", line: "AddressFamily inet" }
    - { regexp: "PermitRootLogin", line: "PermitRootLogin yes" }
    - { regexp: "PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "PasswordAuthentication", line: "PasswordAuthentication no" }  
  notify: 
    - restart sshd
  tags: sshd
- name: "更改系统limits"
  pam_limits:
    dest: "/etc/security/limits.conf"
    domain: '{{ item.limit_domain }}'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_domain: 'root',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: 'root',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
  tags: limits
- name: "更改systemd limits"
  lineinfile:
    dest: "/etc/systemd/system.conf"
    line: "{{ item.line }}"
    state: present
  with_items: 
    - {line: 'DefaultLimitNOFILE=65535' }
    - {line: 'DefaultLimitNPROC=65535' }
  tags: limits
- name: "启用依赖内核模块"
  modprobe:
    name: "{{ item.line }}"
    state: present
  with_items:
    - {line: 'br_netfilter' }
    - {line: 'nf_conntrack_ipv4' }
    - {line: 'bridge' }
    - {line: 'ip_vs' }
    - {line: 'ip_vs_rr' }
    - {line: 'ip_vs_wrr' }
    - {line: 'ip_vs_sh' }
  tags: mod
- name: "修改内核参数"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - {name: 'kernel.sysrq',value: '1' }
    - {name: 'vm.swappiness ',value: ' 0' }
    - {name: 'vm.max_map_count',value: '500000' }
    - {name: 'net.core.somaxconn',value: '8192' }
    - {name: 'fs.file-max',value: '655360' }
    - {name: 'fs.nr_open',value: '52706963' }
    - {name: 'fs.inotify.max_user_instances',value: '8192' }
    - {name: 'fs.inotify.max_user_watches',value: '1048576' }
    - {name: 'net.ipv4.ip_forward',value: '1' }
    - {name: 'net.ipv4.neigh.default.gc_stale_time',value: '120' }
    - {name: 'net.ipv4.conf.all.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.arp_announce ',value: ' 2' }
    - {name: 'net.ipv4.conf.lo.arp_announce',value: '2' }
    - {name: 'net.ipv4.conf.all.arp_announce',value: '2' }
    - {name: 'net.ipv4.tcp_max_tw_buckets ',value: ' 5000' }
    - {name: 'net.ipv4.tcp_syncookies ',value: ' 1' }
    - {name: 'net.ipv4.tcp_max_syn_backlog ',value: ' 1024' }
    - {name: 'net.ipv4.tcp_synack_retries ',value: ' 2' }
    - {name: 'net.ipv6.conf.lo.disable_ipv6 ',value: ' 1' }
    - {name: 'net.ipv6.conf.all.disable_ipv6 ',value: ' 1' }
    - {name: 'net.ipv6.conf.default.disable_ipv6 ',value: ' 1' }
    - {name: 'net.ipv4.tcp_keepalive_time',value: '600' }
    - {name: 'net.ipv4.tcp_keepalive_intvl',value: '30' }
    - {name: 'net.ipv4.tcp_keepalive_probes',value: '10' }
    - {name: 'net.ipv4.tcp_fin_timeout',value: '3' }
    - {name: 'net.ipv4.tcp_max_orphans',value: '655360' }
    - {name: 'net.ipv4.tcp_max_tw_buckets',value: '300000' }
    - {name: 'net.ipv4.ip_local_port_range',value: '20000 60999' }
    - {name: 'net.netfilter.nf_conntrack_max',value: '2310720' }
    - {name: 'net.bridge.bridge-nf-call-iptables',value: '1' }
    - {name: 'net.bridge.bridge-nf-call-ip6tables',value: '1' }
  tags: sysctl
- name: "安装基础应用"
  yum:
    name: "{{ item.line }}"
    state: installed
  with_items:
    - {line: 'vim'}
    - {line: 'mtr'}
    - {line: 'nscd'}
    - {line: 'curl'}
    - {line: 'wget'}
    - {line: 'lsof'}
    - {line: 'lrzsz'}
    - {line: 'rsync'}
    - {line: 'telnet'}
    - {line: 'bash-completion'}
    - {line: 'nmap-ncat'}
    - {line: 'net-tools'}
    - {line: 'nfs-utils'}
    - {line: 'yum-utils'}
  tags: install_app
- name: "启用dns缓存"
  systemd:
    name: nscd
    state: started
