- name: fail when hostname is not specified
  fail:
    msg: "hostname not specified"
  when:
    - hostname is not defined
- name: "change hostname"
  hostname:
    name: "{{ hostname|quote }}"
  tags: hostname
- name: Hosts | populate apiserver_domain_name loadbalancer address into hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ apiserver_domain_name }}$"
    line: "{{ vip }} {{ apiserver_domain_name }}"
    state: present
    backup: yes
    unsafe_writes: yes
- name: "set env file"
  copy:
    src: "ipenv.sh"
    dest: "/etc/profile.d/"
  tags: os_env
- name: "set timezone"
  timezone:
    name: Asia/Shanghai
- name: "add yum repo"
  yum_repository:
    file: CentOS-Base
    name: '{{ item.name }}'
    description: '{{ item.description}}'
    baseurl: '{{ item.baseurl }}'
    gpgkey: "https://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7"
    failovermethod: priority
    gpgcheck: yes
    enabled: yes
  with_items:
    - { name: "base",description: "CentOS-$releasever",baseurl: "https://mirrors.aliyun.com/centos/$releasever/os/$basearch/" }
    - { name: "updates",description: "CentOS-$releasever",baseurl: "https://mirrors.aliyun.com/centos/$releasever/updates/$basearch/" }
    - { name: "extras",description: "CentOS-$releasever",baseurl: "https://mirrors.aliyun.com/centos/$releasever/extras/$basearch/" }
  tags: CentOS-Base
  when: yum_config_internet
- name: "add yum EPEL repo"
  yum_repository:
    file: epel
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    baseurl: "https://mirrors.aliyun.com/epel/7/$basearch"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"
    failovermethod: priority
    gpgcheck: no
    enabled: yes
  tags: epel
  when: yum_config_internet
- name: "backup yum file"
  shell: "if [ ! -d /etc/yum.repos.backup-zdgt ];then mkdir /etc/yum.repos.backup-zdgt; fi && mv -f /etc/yum.repos.d/* /etc/yum.repos.backup-zdgt/"
  ignore_errors: yes
  tags: local-yum
  when: not yum_config_internet
- name: "add local yum"
  template:
    src: "zdgt-k8s.repo.j2"
    dest: "/etc/yum.repos.d/zdgt-k8s.repo"
  tags: local-yum
  when: not yum_config_internet
- name: "install chrony"
  yum:
    name: "chrony"
    state: installed
  tags: ntp
- name: "configure chrony service"
  copy:
    src: "chrony.conf"
    dest: "/etc/chrony.conf"
  notify: 
    - restart chrony
  tags: ntp
- name: "set swap off"
  shell: swapoff -a
- name: "set selinux off"
  selinux:
    state: disabled
  tags: selinux
- name: "set firewalld off"
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  tags: firewalld
- name: "change ssh configure"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "UseDNS", line: "UseDNS no" }
    - { regexp: "AddressFamily", line: "AddressFamily inet" }
    - { regexp: "PermitRootLogin", line: "PermitRootLogin yes" }
    - { regexp: "PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "PasswordAuthentication", line: "PasswordAuthentication no" }  
  notify: 
    - restart sshd
  tags: sshd
- name: "change limits"
  pam_limits:
    dest: "/etc/security/limits.conf"
    domain: '{{ item.limit_domain }}'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_domain: 'root',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: 'root',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
  tags: limits
- name: "change systemd limits"
  lineinfile:
    dest: "/etc/systemd/system.conf"
    line: "{{ item.line }}"
    state: present
  with_items: 
    - {line: 'DefaultLimitNOFILE=65535' }
    - {line: 'DefaultLimitNPROC=65535' }
  tags: limits
- name: "configure kernel mode"
  modprobe:
    name: "{{ item.line }}"
    state: present
  with_items:
    - {line: 'br_netfilter' }
    - {line: 'nf_conntrack_ipv4' }
    - {line: 'bridge' }
    - {line: 'ip_vs' }
    - {line: 'ip_vs_rr' }
    - {line: 'ip_vs_wrr' }
    - {line: 'ip_vs_sh' }
  tags: mod
- name: "change kernel parameter"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - {name: 'kernel.sysrq',value: '1' }
    - {name: 'vm.swappiness ',value: ' 0' }
    - {name: 'vm.max_map_count',value: '500000' }
    - {name: 'net.core.somaxconn',value: '8192' }
    - {name: 'fs.file-max',value: '655360' }
    - {name: 'fs.nr_open',value: '52706963' }
    - {name: 'fs.inotify.max_user_instances',value: '8192' }
    - {name: 'fs.inotify.max_user_watches',value: '1048576' }
    - {name: 'net.ipv4.ip_forward',value: '1' }
    - {name: 'net.ipv4.neigh.default.gc_stale_time',value: '120' }
    - {name: 'net.ipv4.conf.all.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.arp_announce ',value: ' 2' }
    - {name: 'net.ipv4.conf.lo.arp_announce',value: '2' }
    - {name: 'net.ipv4.conf.all.arp_announce',value: '2' }
    - {name: 'net.ipv4.tcp_max_tw_buckets ',value: ' 5000' }
    - {name: 'net.ipv4.tcp_syncookies ',value: ' 1' }
    - {name: 'net.ipv4.tcp_max_syn_backlog ',value: ' 1024' }
    - {name: 'net.ipv4.tcp_synack_retries ',value: ' 2' }
    - {name: 'net.ipv6.conf.lo.disable_ipv6 ',value: ' 1' }
    - {name: 'net.ipv6.conf.all.disable_ipv6 ',value: ' 1' }
    - {name: 'net.ipv6.conf.default.disable_ipv6 ',value: ' 1' }
    - {name: 'net.ipv4.tcp_keepalive_time',value: '600' }
    - {name: 'net.ipv4.tcp_keepalive_intvl',value: '30' }
    - {name: 'net.ipv4.tcp_keepalive_probes',value: '10' }
    - {name: 'net.ipv4.tcp_fin_timeout',value: '3' }
    - {name: 'net.ipv4.tcp_max_orphans',value: '655360' }
    - {name: 'net.ipv4.tcp_max_tw_buckets',value: '300000' }
    - {name: 'net.ipv4.ip_local_port_range',value: '20000 60999' }
    - {name: 'net.netfilter.nf_conntrack_max',value: '2310720' }
    - {name: 'net.bridge.bridge-nf-call-iptables',value: '1' }
    - {name: 'net.bridge.bridge-nf-call-ip6tables',value: '1' }
  tags: sysctl
- name: "install some software"
  yum:
    name: "{{ item.line }}"
    state: installed
  with_items:
    - {line: 'vim'}
    - {line: 'mtr'}
    - {line: 'nscd'}
    - {line: 'curl'}
    - {line: 'wget'}
    - {line: 'lsof'}
    - {line: 'lrzsz'}
    - {line: 'rsync'}
    - {line: 'telnet'}
    - {line: 'bash-completion'}
    - {line: 'nmap-ncat'}
    - {line: 'net-tools'}
    - {line: 'nfs-utils'}
  tags: install_app
- name: "set dns buffer"
  systemd:
    name: nscd
    state: started
